#!/bin/perl -w
use strict;
use Getopt::Long;
use Env;

(my $pgmname = $0) =~ s{.*/}{};
my $usage	= "usage: $pgmname [--help] --language=[c|java]\n";
my %opt = ();
GetOptions( \%opt, "help", "language=s" ) or die "$usage";
die "$usage" if defined $opt{'help'} or !defined $opt{'language'};

chdir("../test") or die "chdir: $!\n";
my $pgm = ($opt{'language'} eq "c" ?  "../$T/mesh" : 
	    "java -cp ../$T/Mesh.jar:$XMTXHIST/libxhist/$T/Xhist.jar Mesh" );
my $ports = "10000 10001 10002";
my @children;

foreach my $i (0 .. 2)
{
    my $pid = fork();
    if ($pid == 0)	# child
    {
	exec("$pgm $i $ports > $i.out");
    }
    else		# parent
    {
        push @children, $pid;
    }
}
