#************************************************************************
#*   Package	: xmt_extern
#*   Synopsis	: source xmt_extern/proto/cshrc
#*   Purpose	: thirdparty dependency .cshrc additions
#*      XMT can be installed on an NFS-exported filesystem that is mounted by
#*      all developers to avoid each developer having to install and configure
#*      it locally. XMT packages can have dependencies on thirdparty tools.
#*      It may be convenient to install those here as well, and make them
#*      available via the same NFS mount. xmt_extern/bin is the recommended
#*      path for thirdparty software invoked by XMT.  $XMT/.cshrc and
#*      $XMT/.bashrc adds this to PATH by default.
#*
#*  Copyright (c) 2018	Visionary Research Inc.  
#*  			legal@visionary-research.com
#*  Licensed under the Apache License, Version 2.0 (the "License");
#*  you may not use this file except in compliance with the License.
#*  You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
#*  
#*  Unless required by applicable law or agreed to in writing, software
#*  distributed under the License is distributed on an "AS IS" BASIS,
#*  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#*  See the License for the specific language governing permissions and
#*  limitations under the License. 
#************************************************************************

# need variables set before referencing them below
if ( ! $?PATH ) then
     setenv PATH "/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin"
endif
if ( ! $?LD_LIBRARY_PATH ) then
     setenv LD_LIBRARY_PATH "/lib:/usr/lib:/usr/local/lib"
endif
if ( ! $?MANPATH ) then
     setenv MANPATH /usr/share/man
endif
setenv XMTEXT	        "$XMT/xmt_extern"

# additional paths installed under $XMTEXT, as described in $XMTEXT/README.md
setenv PATH "${PATH}:$XMTEXT/usr/bin:$XMTEXT/usr/share/clang/scan-build-py-9/bin:$XMTEXT/usr/share/clang/scan-view-9/bin:$XMTEXT/usr/share/clang/scan-build-9/bin:$XMTEXT/usr/lib/llvm-9/bin"
setenv LD_LIBRARY_PATH "${LD_LIBRARY_PATH}:$XMTEXT/usr/lib/x86_64-linux-gnu:$XMTEXT/usr/lib/llvm-9/lib"
setenv MANPATH "${LD_LIBRARY_PATH}:$XMTEXT/usr/share/man:$XMTEXT/usr/share/clang/scan-build-9/man:$XMTEXT/usr/lib/llvm-9/share/man"
