#************************************************************************
#   Package	: mesh
#   $Version:$
#   Copyright 2018 <company name>.  All rights reserved.
#
#   Synopsis	: included automatically by $(XMTBUILD)/proto/Makefile.top
#   Purpose	: Customize make environment for the current package.
#************************************************************************


###  Java language settings
LANGUAGE	= java
BUILD_TGT	= exe
ARCH		= linux_x86
PKG_NM		= mesh
EXE_NM		= Mesh
JAVA_PKGROOT	= .
CFLAGS.java	+= -cp .:$(OBJDIR):$(XMTXHIST)/libxhist/tgt/$(ARCH)/Xhist.jar
#%.java : ../data/%.java	
#	-/bin/rm xhist.*.map
#	$(XMTCM)/bin/git_filter --expand=. --xhist=. $^  > $@

###  C language settings
#LANGUAGE	= c
#BUILD_TGT	= exe
#ARCH		= linux_x86
#PKG_NM		= mesh
#EXE_NM		= mesh
#CFLAGS.c	+= -g -DXHIST -I$(XMTXHIST)/libxhist/src
#LIBS		= $(XMTXHIST)/libxhist/tgt/$(ARCH)/libXhist.a 
## gcov test coverage flags
#CFLAGS.c	+= -ftest-coverage -fprofile-arcs	
#LDFLAGS.c	+= -lgcov --coverage
#%.c : ../data/%.c	
#	-/bin/rm xhist.*.map
#	$(XMTCM)/bin/git_filter --expand=. --xhist=. $^  > $@

gcov:
	gcov	--object-directory $(OBJDIR) 		\
		--demangled-names 			\
		--branch-probabilities			\
		--function-summaries			\
		--human-readable			\
		--use-colors				\
