#************************************************************************
#   Package	: mesh
#   $Version:$
#   Copyright 2018 <company name>.  All rights reserved.
#
#   Synopsis	: included automatically by $(XMTBUILD)/proto/Makefile.top
#   Purpose	: Customize make environment for the current package.
#************************************************************************
LANGUAGE	= c
ARCH		= linux_x86
CFLAGS.c	+= -g -DXHIST -I$(XMTXHIST)/libxhist/src
BUILD_TGT	= exe
LIBS		= $(XMTXHIST)/libxhist/tgt/$(ARCH)/libxhist.a 

# if gcov test coverage desired
CFLAGS.c	+= -ftest-coverage -fprofile-arcs	
LDFLAGS.c	+= -lgcov --coverage

mesh.c : ../data/mesh.c	
	-/bin/rm xhist.*.map
	$(XMTCM)/bin/git_filter --expand=. --xhist=. $^  > $@

gcov:
	gcov	--object-directory $(OBJDIR) 		\
		--demangled-names 			\
		--branch-probabilities			\
		--function-summaries			\
		--human-readable			\
		--use-colors				\
		$(allsrcs)
