#!/bin/perl -w
use strict;
use Getopt::Long;
use Env;

(my $pgmname = $0) =~ s{.*/}{};
my $usage	= "usage: $pgmname [--help] --language=[c|java]\n";
my %opt = ();
GetOptions( \%opt, "help", "language=s" ) or die "$usage";
die "$usage" if defined $opt{'help'} or !defined $opt{'language'};
my $pgm = ($opt{'language'} eq "c" ? "../$T/mesh" : "java ../$T/Mesh" );



my $ports = "10000 10001 10002 10003 10004 10005 10006 10007 10008 10009";
my @children;
foreach my $i (0 .. 9)
{
    my $pid = fork();
    if ($pid == 0)	# child
    {
	exec("$pgm $i $ports");
    }
    else
    {
        push @children, $pid;
    }
}

# wait for user intput, then reap child pids & exit 
print "Press ENTER to terminate test...\n"; 
<STDIN>;
kill 'USR1', @children;	# force trace log to be written
sleep 2;		# wait for that to complete
kill 'INT', @children;	# then terminate the test
