#!/usr/bin/env perl
use strict;
use Env;

(my $pgmname = $0) =~ s{.*/}{};
my $usage	= "usage: $pgmname [c|java]\n";
die "$usage" if $#ARGV != 0;
die "$usage" if $ARGV[0] ne "c" && $ARGV[0] ne "java";

my $pgm = ($ARGV[0] eq "c" ?  "$XMTXHIST/test/hello/$T/hello" : 
    "java -cp $XMTXHIST/test/hello/$T/Hello.jar:$XMTXHIST/libxhist/$T/Xhist.jar Hello" );

exec($pgm);
