#************************************************************************
#   Package	: xhist
#   $Version:$
#    Copyright 2018 Visionary Research Inc.   All rights reserved.
#*   			legal@visionary-research.com
#*   Licensed under the Apache License, Version 2.0 (the "License");
#*   you may not use this file except in compliance with the License.
#*   You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
#*   
#*   Unless required by applicable law or agreed to in writing, software
#*   distributed under the License is distributed on an "AS IS" BASIS,
#*   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#*   See the License for the specific language governing permissions and
#*   limitations under the License. 
#
#   Synopsis	: included automatically by $(XMTBUILD)/proto/Makefile.top
#   Purpose	: Customize make environment for the current package.
#************************************************************************

ifdef do_vars
#************************************************************************
# DO ALL VARIABLE ASSIGNMENTS HERE
#************************************************************************

CFLAGS.java	+= -cp .:$(OBJDIR):$(XMTXHIST)/libxhist/tgt/$(ARCH)/Xhist.jar
CFLAGS.c	+= -g -DXHIST -I$(XMTXHIST)/libxhist/src 
LIBS.c		+= $(XMTXHIST)/libxhist/tgt/$(ARCH)/libXhist.a	
# gcc requires the -lpthread flag to be at the end of the commandline
LD.append	= -lpthread


endif
ifdef do_rules
#************************************************************************
# DO TARGET RULE OVERRIDES HERE
#************************************************************************

# instrument sources for xhist:
#  cd to $(DATADIR) (where the uninstrumented src resides)
#  write all instrumented sources to $(SRCDIR) for compilation
#  write all xhist_map files to $(TESTDIR) directory 
instrument:
	(cd $(DATADIR) ;				\
	    for f in *.orig ; do			\
		s=$${f%.orig};				\
		m=$(CURDIR)/$(TESTDIR)/$$s.xmap; 	\
		$(XMTCM)/bin/git_filter --expand=. --xhist=. --xhist_map=$$m \
			--fname=$$s  < $$f > $(SRCDIR)/$$s ;	\
	    done					\
	)

c: instrument
	$(MAKE) LANGUAGE=c ARCH=linux_x86 exe

java: instrument
	$(MAKE) LANGUAGE=java ARCH=jre lib


#************************************************************************
endif
